version: '3.1'

services:
  react-dnd-ax:
    build: .
    image: react-dnd-ax
    container_name: react-dnd-ax
    command: npm run storybook
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "9001:9001"
